
services:
  api:
    build: .
    container_name: fastapi_poetry_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: fastapi_db
    depends_on:
      mongo:
        condition: service_healthy
    command: poetry run uvicorn fast_api.app:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
